version: "3.9"
services:
  driver-accounting-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/DriverAccounting_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bestuser
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB:DriverAccounting_db
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:bestuser
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: